### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by imcallister101** [dANamON/StockPi#1]
Working through troubleshooting the following error. Saw your Raspberry Pi YouTube demo and doing my best to recreate it. 

```
Traceback (most recent call last):
  File "BeautifulSoupTicker.py", line 117, in <module>
    tickers()
  File "BeautifulSoupTicker.py", line 56, in tickers
    price3 = float(soup3.find_all('div', {'class':'My(6px) Pos(r) smartphone_Mt(6px)'})[0].find('span').text.replace(',',''))
**IndexError: list index out of range**
```

**Comment by dANamON** [comment]
Were you able to fix the issue?

**Comment by imcallister101** [comment]
Yeah, thanks for asking. 

It was a me issue while editing ticker3.

Reverting back to your code, everything worked like a charm. 

-Ian

**Comment by dANamON** [comment]
Great! Glad to hear it.
